### ISSUE TITLE
Fork at https://github.com/dschalk/react-mobservable-boilerplate

### ISSUE THREAD

**Issue by dschalk** [mweststrate/mobservable-react-boilerplate#1]
The fork at [https://github.com/dschalk/react-mobservable-boilerplate](https://github.com/dschalk/react-mobservable-boilerplate) might be of some general interest. I don't see a neat way to merge it with the master. If you would like for it to be a branch, just tell me how to proceed. Would I need to make a pull request in order to create a branch? I have made pull requests in the past in order to add or modify files in master versions, but I have yet to create a branch.

My fork produces console log output which confirms that mobservable eliminates unnecessary rendering. It shows how 'extends ReactComponent' can replace 'React.createClass', and how 'this.store = todoStore' in the constructor eliminates the need for mutable props, which seem to viewed as  an anti-pattern at Facebook. The React props object is left empty in my fork. 

My fork also demonstrates that when functions are created with the ' => ' arrow pattern, there is no need for '.bind(this)' anywhere in the code. 

I am not suggesting that my fork shows a superior way of doing things. It merely shows some alternatives and provides some reassuring feedback in the console log. Developers who want to use JS6 class syntax to construct components might be interested in seeing how I accomplished it. 

-- David Schalk

**Comment by mweststrate** [comment]
Thanks! I think a separate branch is a good idea indeed. (And as ES6 gains more ground it will probably be master someday). I'm gonna take a detailed look soon. You had some changes in the webpack, package and eslit setup as well, where those intended? If so, can you motivate why you changed this setup?

Tnx!

Michel

**Comment by dschalk** [comment]
Hey Michael,
 
I neglected to check this site and didn't realize that you had responded to my suggestion.

I'll see what I changed, other than syntax. I'm sure I didn't have any strong feelings about what I changed. I was doing some experimenting and ended up with what I pushed to Github. I do recall wondering why you made a mobservable object an attribute of the React props object. I just declared it in the constructor, something like "this.data = data". I wasn't sure what the consequence would be. Everything seemed to work so I left it as it was. Is anything gained by putting mobservable objects in the React props object?

Please take a look at [http://schalk.ninja]{http://schalk.ninja) and tell me what you think. I made some mobservable roll-over buttons and also demonstrated the difference between defining a method in a mobservable encapsulated object or attaching it from the outside. That was a you graciously answered for me.  The code is at [https://github.com/dschalk/mobservable-react-buttons] (https://github.com/dschalk/mobservable-react-buttons).

David

**Comment by dschalk** [comment]
I left a message in closed comment at the main mobservable repo. I'm cutting and pasting here since I don't know how often you see messages in closed comments. 

Here's a link that demonstrates the distinction between defining methods internally or externally: [http://schalk.ninja](http:/schalk.ninja) . Every invocation of "render()" causes an internally defined method to execute, even though nothing related to the method changes. It executes every time I roll over the rollover buttons.The code is at [https://github.com/dschalk/mobservable-react-buttons](https://github.com/dschalk/mobservable-react-buttons).    

The main point of this little project is to show that mobservable can facilitate the creation of highly functional, good-looking rollover buttons. The group buttons resemble ordinary select/option form buttons, but when a user writes in a name not included in the buttons, they all become unselected. And when a user enters a name which is included among the buttons, the corresponding button lights up. Making an HTML form do all of this would be an ugly hack. With mobservable, it is easy and natural. Buttons light up whenever 'group' has a corresponding value. It's all automated by one simple method in a mobservable-encapsulated object.

**Comment by mweststrate** [comment]
Hey @dschalk , I watch all the mobservable projects, just had a busy weekend ;-). I new cool stuff could be done by making mouse events observable, just didn't get around to play with it myself. I'm cleaning up the boilerplate project at the moment, to make it smaller, and added a separate repo for todoMVC, in which I applied your ES6 syntax. Especially the event handlers are clean this way! Without additional binds in the constructor. I didn't know that trick, so thanks for that :)
